In [1]:
%load_ext autoreload
%autoreload 2

In [33]:
import networkx as nx
import sys
import random
sys.path.append('../src/')
from random_graph import RandGraph
import pandas as pd
import numpy as np

## Step function
At each step, we set the paths of a bunch of actors and update the nodes list accordingly.

In [10]:
g = RandGraph()
g.actors

{763: <random_graph.Actor at 0x9cb5358>,
 153: <random_graph.Actor at 0x9cb5320>,
 134: <random_graph.Actor at 0x9cb55c0>,
 256: <random_graph.Actor at 0x9cb55f8>,
 738: <random_graph.Actor at 0x9cb5668>}

In [11]:
g.init_actors()

[1, 12, 5]
[0, 12, 14, 7]


In [12]:
g.graph.nodes(data=True)

NodeDataView({0: {'actors': None}, 1: {'actors': [763]}, 2: {'actors': None}, 3: {'actors': None}, 4: {'actors': None}, 5: {'actors': None}, 6: {'actors': None}, 7: {'capacity': 10, 'actors': None}, 8: {'capacity': 1, 'actors': None}, 9: {'capacity': 7, 'actors': None}, 10: {'capacity': 4, 'actors': None}, 11: {'capacity': 9, 'actors': None}, 12: {'capacity': 9, 'actors': None}, 13: {'capacity': 9, 'actors': None}, 14: {'capacity': 1, 'actors': None}, 15: {'capacity': 6, 'actors': None}, 16: {'capacity': 9, 'actors': None}, 17: {'capacity': 9, 'actors': None}})

In [17]:
g.move_actors()

In [18]:
g.graph.nodes(data=True)

NodeDataView({0: {'actors': None}, 1: {'actors': []}, 2: {'actors': None}, 3: {'actors': None}, 4: {'actors': None}, 5: {'actors': []}, 6: {'actors': None}, 7: {'capacity': 10, 'actors': [153]}, 8: {'capacity': 1, 'actors': None}, 9: {'capacity': 7, 'actors': None}, 10: {'capacity': 4, 'actors': None}, 11: {'capacity': 9, 'actors': None}, 12: {'capacity': 9, 'actors': []}, 13: {'capacity': 9, 'actors': None}, 14: {'capacity': 1, 'actors': []}, 15: {'capacity': 6, 'actors': None}, 16: {'capacity': 9, 'actors': None}, 17: {'capacity': 9, 'actors': None}})

In [91]:
data = np.zeros((1,len(g.core_nodes)))

In [92]:
def get_loading(g):
    values = []
    for node in g.graph.nodes(data=True):
        if 'capacity' in node[1]:
            
            if node[1]['actors']:
                values.append(len(node[1]['actors'])/float(node[1]['capacity']))
            else:
                values.append(0.0)
    return np.array([values])

In [93]:
data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [94]:
get_loading(g)

array([[0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

In [95]:
np.vstack((data, get_loading(g)))

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

In [96]:
def step(g, n= 10):
    data = np.zeros((1,len(g.core_nodes)))
    for i in range(n):
        g.init_actors()
        g.move_actors()
        values = get_loading(g)
        data = np.vstack((data, values))
    return data

In [97]:
g = RandGraph()

In [98]:
data = step(g)

[4, 14, 8, 12, 6]
[1, 13, 8, 5]
[1, 13, 8, 5]
[1, 13, 15, 4]
[1, 13, 8, 5]


In [99]:
data

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.33333333, 0.25      , 0.        , 0.        ,
        0.        ],
       [0.        , 0.25      , 0.        , 0.        , 0.        ,
        0.        , 0.66666667, 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.125     , 0.        , 0.        , 0.        ,
        0.5       , 0.33333333, 0.        , 0.33333333, 0.        ,
        0.        ],
       [0.        , 0.125     , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.

In [100]:
df = pd.DataFrame(data, columns=g.core_nodes)

In [101]:
df

7      8    9    10   11   12        13    14        15   16   17
0   0.0  0.000  0.0  0.0  0.0  0.0  0.000000  0.00  0.000000  0.0  0.0
1   0.0  0.000  0.0  0.0  0.0  0.0  0.333333  0.25  0.000000  0.0  0.0
2   0.0  0.250  0.0  0.0  0.0  0.0  0.666667  0.00  0.000000  0.0  0.0
3   0.0  0.125  0.0  0.0  0.0  0.5  0.333333  0.00  0.333333  0.0  0.0
4   0.0  0.125  0.0  0.0  0.0  0.0  0.000000  0.00  0.000000  0.0  0.0
5   0.0  0.000  0.0  0.0  0.0  0.0  0.000000  0.00  0.000000  0.0  0.0
6   0.0  0.000  0.0  0.0  0.0  0.0  0.000000  0.00  0.000000  0.0  0.0
7   0.0  0.000  0.0  0.0  0.0  0.0  0.000000  0.00  0.000000  0.0  0.0
8   0.0  0.000  0.0  0.0  0.0  0.0  0.000000  0.00  0.000000  0.0  0.0
9   0.0  0.000  0.0  0.0  0.0  0.0  0.000000  0.00  0.000000  0.0  0.0
10  0.0  0.000  0.0  0.0  0.0  0.0  0.000000  0.00  0.000000  0.0  0.0