In [1]:
%load_ext autoreload
%autoreload 2

In [23]:
import networkx as nx
import sys
import random
sys.path.append('../src/')
from random_graph import RandGraph
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [170]:
g = RandGraph(actors=200, moving=5)

## Reward
We would like to measure the network congestion. We can use the Ratios of Means.


In [91]:
denom = np.sum(list(nx.get_node_attributes(g.graph,'capacity').values()),dtype=float)

In [92]:
[len(x) for x in nx.get_node_attributes(g.graph, 'actors').values() if x]

[]

In [93]:
ratio = num/denom

In [94]:
ratio

0.0

In [95]:
reward = 1.0 - ratio

In [96]:
reward

1.0

In [164]:
data, nodes, rewards = g.step()

In [165]:
cols = nodes + ['reward']

In [166]:
rewards

[0.94029850746268662,
 0.88059701492537312,
 0.83582089552238803,
 0.79104477611940305,
 0.71641791044776126,
 0.64179104477611948,
 0.59701492537313428,
 0.53731343283582089,
 0.4925373134328358,
 0.43283582089552242]

In [153]:
len(rewards)

10

In [154]:
r = np.zeros((len(rewards)+1, 1))
r[1:] = np.array([rewards]).T

In [155]:
r.shape

(11, 1)

In [156]:
data.shape

(11, 11)

In [157]:
rows = np.hstack((data, r))

In [158]:
rows.shape

(11, 12)

In [159]:
df = pd.DataFrame(rows, columns=cols)

In [160]:
df

9        10   11   12        13   14        15   16    17   18   19  \
0   0.0  0.000000  0.0  0.0  0.000000  0.0  0.000000  0.0  0.00  0.0  0.0   
1   0.0  0.000000  0.0  0.0  0.000000  0.0  0.000000  0.4  0.75  0.0  0.0   
2   0.0  0.444444  0.0  0.5  0.142857  0.0  0.000000  0.2  0.25  0.0  0.0   
3   0.0  0.111111  0.0  0.5  0.000000  0.0  0.285714  0.6  0.50  0.0  0.0   
4   0.0  0.111111  0.0  0.5  0.000000  0.0  0.000000  1.0  1.00  0.0  0.0   
5   0.0  0.222222  0.0  1.0  0.000000  0.0  0.000000  0.8  0.50  0.0  0.0   
6   0.0  0.222222  0.0  1.0  0.000000  0.0  0.142857  0.6  1.00  0.0  0.0   
7   0.0  0.444444  0.0  1.0  0.000000  0.0  0.142857  0.4  0.75  0.0  0.0   
8   0.0  0.444444  0.0  0.5  0.142857  0.0  0.142857  0.2  1.00  0.0  0.0   
9   0.0  0.222222  0.0  0.5  0.000000  0.0  0.142857  0.6  0.75  0.0  0.0   
10  0.0  0.111111  0.0  1.0  0.142857  0.0  0.000000  0.6  1.00  0.0  0.0   

    reward  
0      0.0  
1      NaN  
2      NaN  
3      NaN  
4      NaN  
5      NaN  
6      NaN  
7      NaN  
8      NaN  
9      NaN  
10     NaN

The network is not so much penalized by a saturating node. 

In [141]:
num = np.array([len(x) if x else 0 for x in nx.get_node_attributes(g.graph.subgraph(g.core_nodes), 'actors').values() ])

In [116]:
denom = np.array(list(nx.get_node_attributes(g.graph, 'capacity').values()), dtype=float)

In [174]:
num

array([2, 2, 1, 1, 0, 1, 0, 3, 0, 0, 1])

In [140]:
denom

array([  6.,  10.,   2.,   7.,   2.,   9.,   8.,  10.,   4.,   5.,   3.])

In [175]:
num/denom

array([ 0.33333333,  0.2       ,  0.5       ,  0.14285714,  0.        ,
        0.11111111,  0.        ,  0.3       ,  0.        ,  0.        ,
        0.33333333])

In [143]:
np.mean(num/denom)

0.17460317460317457

In [172]:
data, nodes, rewards = g.step(reward_type='mr')

In [173]:
rewards

[0.79292929292929293,
 0.64141414141414144,
 0.65656565656565657,
 0.61363636363636365,
 0.66161616161616155,
 0.5505050505050505,
 0.59090909090909083,
 0.69191919191919193,
 0.59090909090909083,
 0.56565656565656552]

In [201]:
import time

In [233]:
max_iter = 50
prog = 0
for i in range(max_iter):
    # length bar 50 print every 2 % prog
    curr_prog = round(i/float(max_iter),1) /0.1
#     print('.',sep='',end='', flush=False)
    
    if curr_prog != prog:
#         print('|' ,sep='',end='', flush=True)        
        prog = curr_prog
        
    print('\r%% %d%10s' % (round(i/float(max_iter)*100), '|'*int(curr_prog)), sep='',end=' ', flush=True)
    time.sleep(0.25)

% 98|||||||||| 

In [237]:
import os
import binascii

In [235]:
os.urandom(4)

b'\xc8\x14J\xf0'

In [238]:
binascii.hexlify(os.urandom(4))

b'252110a9'