In [17]:
%load_ext autoreload
%autoreload 2

In [37]:
import networkx as nx
import sys
import random
sys.path.append('../src/')
from random_graph import RandGraph
from deep_q_learning import Memory
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import random

In [5]:
a = 0.25 * np.random.randn(6,3) + 0.5

In [6]:
a

array([[-0.10071575,  0.74152188,  0.88932919],
       [ 0.75780648,  0.17202332,  0.61171844],
       [ 0.97063191,  0.87049418,  0.6504853 ],
       [ 0.61334287,  1.00850831,  0.20860445],
       [ 0.1951762 ,  0.726078  ,  0.64518235],
       [ 0.01623579,  0.31691633,  0.37398768]])

In [14]:
b = np.where(a > 1., np.ones_like(a), a)

In [15]:
c = np.where(b < 0., np.zeros_like(b), b)

In [16]:
c

array([[0.        , 0.74152188, 0.88932919],
       [0.75780648, 0.17202332, 0.61171844],
       [0.97063191, 0.87049418, 0.6504853 ],
       [0.61334287, 1.        , 0.20860445],
       [0.1951762 , 0.726078  , 0.64518235],
       [0.01623579, 0.31691633, 0.37398768]])

In [38]:
memory = Memory(5, 3, 6)

In [39]:
memory.load(np.array([[5,5,5]]), np.array([[1,1,1,1,1,1]]), np.array([[6,6,6]]), 8)

In [40]:
memory.memory

array([[5.        , 5.        , 5.        , 6.        , 6.        ,
        6.        , 8.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan],
       [0.3411579 , 0.52387203, 0.06680413, 0.41278237, 0.54194759,
        0.5909095 , 0.29821163, 0.23510306, 0.80028095, 0.28252855,
        0.54986528, 0.31665106, 0.64271574],
       [0.28144351, 0.16011138, 0.72356183, 0.15309042, 0.52018076,
        0.66977716, 0.4765392 , 0.40848617, 0.46631969, 0.24463861,
        0.40157004, 0.41489041, 0.56914743],
       [0.48735014, 0.59279064, 0.58035733, 0.23308256, 0.67581324,
        0.45376015, 0.55527382, 0.25655958, 0.21690585, 0.20861027,
        0.45693357, 0.3768836 , 0.04934152]])

In [41]:
memory.memory.shape

(5, 13)

In [42]:
memory.shape

(5, 13)

In [57]:
states, actions, next_states, rewards = memory.replay(3)

In [58]:
states

array([[5.        , 5.        , 5.        ],
       [0.3411579 , 0.52387203, 0.06680413],
       [0.3411579 , 0.52387203, 0.06680413]])

In [59]:
actions

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ],
       [0.23510306, 0.80028095, 0.28252855, 0.54986528, 0.31665106,
        0.64271574],
       [0.23510306, 0.80028095, 0.28252855, 0.54986528, 0.31665106,
        0.64271574]])

In [60]:
next_states

array([[6.        , 6.        , 6.        ],
       [0.41278237, 0.54194759, 0.5909095 ],
       [0.41278237, 0.54194759, 0.5909095 ]])

In [61]:
rewards

array([[8.        ],
       [0.29821163],
       [0.29821163]])

In [62]:
g = RandGraph(graph_type='simple')

In [132]:
from deep_q_learning import ActionSpace

In [133]:
actions = ActionSpace(g)

In [134]:
actions.combinations

[(3,),
 (4,),
 (5,),
 (6,),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 5),
 (4, 6),
 (5, 6),
 (3, 4, 5),
 (3, 4, 6),
 (3, 5, 6),
 (4, 5, 6),
 (3, 4, 5, 6)]

In [137]:
actions.sample()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [138]:
actions.get_nodes(np.array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]]))

[5, 6]