In [1]:
% load_ext autoreload
% autoreload 2

In [2]:
import networkx as nx
import sys
import random
sys.path.append('../src/')
from random_graph import RandGraph
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import random

In [3]:
from deep_q_learning import DQN, ActionSpace

/home/michael/tensorflow/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [4]:
g =RandGraph(graph_type='simple', actors=10000)

In [5]:
dqn = DQN(g)

In [6]:
dqn.train(10)

In [7]:
dqn.total_rewards

[0.0,
 0.0,
 0.0,
 0.0,
 1.4285714285714286,
 0.0,
 0.5833333333333334,
 0.0,
 0.0,
 0.5714285714285714]

### Save the model

In [8]:
# create specific folder
import os

In [9]:
path = '../models/test/'

In [11]:
dqn.model.save(path+'model.h5')

## Loading the model

In [12]:
from keras.models import load_model

In [13]:
model2 = load_model(path+'model.h5')

In [14]:
model2.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
values (InputLayer)             (None, 4)            0                                            
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 32)           160         values[0][0]                     
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 32)           1056        dense_1[0][0]                    
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 15)           495         dense_2[0][0]                    
__________________________________________________________________________________________________
mask (Inpu

## Predicting next action

In [16]:
state = g.get_loading()
state

array([[0.85714286, 1.        , 1.        , 0.        ]])

In [18]:
dqn.length_actions

15

In [21]:
q_val = model2.predict([state, np.ones((1,15))])
q_val

array([[ 0.16660704,  0.23473284,  0.23478769, -0.03119303,  0.26462197,
         0.04655992,  0.00151337,  0.00900863, -0.0886941 ,  0.25287724,
        -0.07245485,  0.10775968, -0.20975241,  0.25758255, -0.03484388]],
      dtype=float32)

In [23]:
idx = np.argmax(q_val)

In [24]:
act_vect = np.zeros((1,15))

In [25]:
act_vect[:,idx] = 1.

In [26]:
act_vect

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
dqn.action_space.get_nodes(act_vect)

[3, 4]

### Pickle action space

In [28]:
import pickle

In [32]:
with open(path+'actionspace.pkl', 'wb') as f:
    pickle.dump(dqn.action_space,f)